### ISSUE TITLE
Question error

### ISSUE THREAD

**Issue by stefancode** [certificationy/php-pack#11]
LINE - 405 
correct answer from localhost testing is: 
Notice: Undefined variable: data in C:\xampp\htdoc...
0 

```
question: |
            Assuming UTF-8 encoding, what is the value of $count?
            $count = strlen($data);
answers:
  - { value: '0', correct: false }
  - { value: '4', correct: false }
  - { value: '5', correct: true }
  - { value: '7', correct: false }
```

but if you put $data inside single quotes '' than result is 5.
--> '$data'

**Comment by mickaelandrieu** [comment]
This question doesnt exists in this pack ... are you sure this it comes from this pack ?

Googling a little bit, I found the value of $data : `$data = '$1Ä2';`

**Comment by stefancode** [comment]
sorry, this was from another repo... $1Ä2 != 5

**Comment by mickaelandrieu** [comment]
@stefancode I don't know, you should ask this another repo's maintainer :cat:
