### ISSUE TITLE
Static methods don't have access to the self keyword?

### ISSUE THREAD

**Issue by mazhuravlev** [certificationy/php-pack#15]
Is there an error? 

https://github.com/certificationy/php-pack/blob/eea5c4b851e58cb190cc1c97f4c969b072bec39f/data/questions.yml#L236

**Comment by stollr** [comment]
@seregazhuk Yes, the referenced answer cannot be correct, like @mazhuravlev says. `self` is available in any method as it refers to the class.

**Comment by mickaelandrieu** [comment]
it's an error => https://3v4l.org/4qOGG would you mind to create a pull request to fix it  please? or change ``self`` by ``$this`` ^^

**Comment by 20uf** [comment]
@mickaelandrieu This issue is solved, it can be closed?

**Comment by mickaelandrieu** [comment]
Yes ! :)
