### ISSUE TITLE
Suggest question statement change (concerning array internal pointer)

### ISSUE THREAD

**Issue by mazhuravlev** [certificationy/php-pack#16]
Current [question](https://github.com/certificationy/php-pack/blob/eea5c4b851e58cb190cc1c97f4c969b072bec39f/data/questions.yml#L530) is quite ambiguos:

> Which of the following functions are used with the internal array pointer to accomplish an action?

Also there is [error](https://github.com/certificationy/php-pack/blob/eea5c4b851e58cb190cc1c97f4c969b072bec39f/data/questions.yml#L536) in answer definition (correct: next)

I suggest this version:
- Which of the following functions affects internal array pointer position? (answers: prev, next)

**Comment by mickaelandrieu** [comment]
Agree => go pull request please :)
