### ISSUE TITLE
clarification regarding question (pcre matching)

### ISSUE THREAD

**Issue by stesie** [certificationy/php-pack#19]
Regarding https://github.com/certificationy/php-pack/blob/master/data/questions.yml#L697

The question doesn't (explicitly) state that it is about matching the string as a whole. The answer flagged correct is the only one that does that ... however if it is just about matching the string (i.e. partially) then

```
php > var_dump(preg_match('/^[hp1-5]*\-.*/i', 'PhP5-rocks'));
int(1)
php > var_dump(preg_match('/[hp1-5]*\-.?/', 'PhP5-rocks'));
int(1)
php > var_dump(preg_match('/[hp][1-5]*\-.*/', 'PhP5-rocks'));
int(0)
php > var_dump(preg_match('/[PhP]{3}[1-5]{2,3}\-.*$/', 'PhP5-rocks'));
int(0)
php > var_dump(preg_match('/[a-z1-5\-]*/', 'PhP5-rocks'));
int(1)
```

... two more answers are correct.

So IMHO either the question should explicitly state that it is about matching the whole string or otherwise two extra answers should be flagged correct, hence changing it to a multiple choice question.

**Comment by 20uf** [comment]
still relevant ?

**Comment by mickaelandrieu** [comment]
As the link provided returns a 404, no.

Sorry @stesie, let us know if you have still an issue with it :)

**Comment by stesie** [comment]
@mickaelandrieu well you just moved the question to a different file, question & answers unchanged, hence the problem actually remains.

Updated link, this time with commit hash instead of master: https://github.com/certificationy/php-pack/blob/c17e1e02320c2e24bf0f8ffc889578eb9e91f24a/data/strings-patterns.yml#L139
