### ISSUE TITLE
fwrite("php://stderr") doesn't return STDERR resource

### ISSUE THREAD

**Issue by stesie** [certificationy/php-pack#20]
Regarding https://github.com/certificationy/php-pack/blob/master/data/questions.yml#L108

`fwrite` expects two arguments, a resource and a string to output and returns the number of bytes written.  I can't think of a case when (and why) it should return a STDERR resource. So I think the answer is clearly wrong

``` console
$ php -r 'fopen("php://stderr");'
PHP Warning:  fopen() expects at least 2 parameters, 1 given in Command line code on line 1
```

**Comment by 20uf** [comment]
still relevant ?

**Comment by mickaelandrieu** [comment]
Not anymore ;)

Thanks for report @stesie!
