### ISSUE TITLE
Email address public?

### ISSUE THREAD

**Issue by flemzord** [certificationy/php-pack#31]
Hello,

In the travis configuration, we find an email address.
Why not hide it? Because we do not need to know it :)

Valid for all projects (symfony-pack, etc)

Regards,
Maxence

**Comment by mickaelandrieu** [comment]
You already know my email in the composer configuration file (https://github.com/certificationy/php-pack/blob/master/composer.json#L11), believe me it's not a big deal.

Feel free to contact me by email if you need to :)
